# Generated by Django 4.2.25 on 2025-11-17 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_status', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', max_length=10)),
                ('profile_pic', models.ImageField(blank=True, default='profile_pics/default.jpg', upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('valid_until', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('bug', 'Bug or Error'), ('suggestion', 'Feature Suggestion'), ('prompt', 'Prompt Issue'), ('ui', 'UI/UX Issue'), ('other', 'Other')], max_length=15)),
                ('llm_prompt', models.TextField(blank=True, help_text='Paste the prompt you used, if relevant.')),
                ('llm_response', models.TextField(blank=True, help_text="Paste or describe the LLM's response, if relevant.")),
                ('description', models.TextField(help_text='Describe your feedback in detail.')),
                ('rating', models.PositiveSmallIntegerField(default=0, help_text='Rate your experience (1 - worst, 5 - best).')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='feedback/')),
                ('transcript', models.FileField(blank=True, help_text='Upload your chat transcript (TXT). Do not upload sensitive information.', null=True, upload_to='transcripts/')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='in_progress', max_length=20)),
                ('admin_response', models.TextField(blank=True, help_text='Admin/staff response to feedback (if any).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
