# Generated by Django 4.2.25 on 2025-11-17 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_organisation_organisationmembership'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organisationmembership',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='organisationmembership',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
